### ISSUE TITLE
Is TraceURL correct?

### ISSUE THREAD

**Issue by murraybauer** [jed/where-durableobjects-live#1]
I noticed your code is using this trace URL:
```
let traceUrl = 'https://www.cloudflare.com/cdn-cgi/trace'
````

And I noticed the https://workers.cloudflare.com/ page which displays the response time to your neasest POP actually uses https://1.1.1.1/cdn-cgi/trace instead.

For me 1.1.1.1 says my nearest POP is Brisbane (correct), where as cloudflare.com says Sydney.

Do you know the difference? Do you believe you are using the correct one?

**Comment by jed** [comment]
I can't believe I missed this for so long... I really don't know the difference, to be honest. IIRC Workers aren't allowed to fetch bare IP addresses, but this might not be true for CF-internal stuff.
