### ISSUE TITLE
Trying to understand project

### ISSUE THREAD

**Issue by ducan-ne** [jed/where-durableobjects-live#5]
I have a question, how it actually creates DO around the world (every 5m), is that a external cron calls https://github.com/helloimalastair/where-durableobjects-live/blob/4c9cb69b04adf975136ca34c93256f2f831f30bc/apps/pages/src/routes/ping/%2Bserver.ts#L4 every 5m (with all cities so every colo will be created)? I don't see any code for this though.. I also try to read that worker has a cron that runs some tasks in background but most of them are queries.

**Comment by helloimalastair** [comment]
@ducan-ne that is a good point. Checks are made by pointing a Cloudflare [Load Balancing Monitor](https://developers.cloudflare.com/load-balancing/monitors/) at the `ping` route that you found. The Monitor is set to trigger a request from every Cloudflare Datacenter once a minute.

**Comment by helloimalastair** [comment]
Closing this, feel free to reopen if you need more clarification.
